### ISSUE TITLE
Instantiation of fields being duplicated

### ISSUE THREAD

**Issue by itsonlyfrans** [JohnBaracuda/Runtime-Monitoring#16]
Unity 2022.2.1f1
Windows 10, 64bit

Whenever I click play, the fields that are being monitored normally. However, when I stop and play again, it duplicates the label in the game scene.

Few things I noticed..
- The scene "freezes" a bit after hitting play, and then "DontDestroyOnLoad" is loaded. 
- Changing Play Mode settings to "Reload Domain" it will clear the previous field being monitored and instantiate only one.
- Altering script in any way will produce same results as enabling "reload domain" play mode option.
I've attached a video showing everything I've explained.

### https://vimeo.com/784086061 (File is over 10mb, can't upload here)

![image](https://user-images.githubusercontent.com/46535667/209428049-c96f8ec5-dc50-4395-954b-26fb61e37e5d.png)

**Comment by JohnBaracuda** [comment]
Better late than never :)
Make sure you are using version 3.4.1. Entering playmode without a domain reload is supported since 3.4.1 so I guess that updating should fix the issue.  If not please let me know.
