### ISSUE TITLE
ambiguous reference between

### ISSUE THREAD

**Issue by XeonG** [JohnBaracuda/Runtime-Monitoring#18]
`Library\PackageCache\com.baracuda.runtime-monitoring@3.5.2\Editor\IL2CPPBuildExtensions.cs(70,55): error CS0104: 'AssemblyFlags' is an ambiguous reference between 'UnityEditor.Compilation.AssemblyFlags' and 'System.Reflection.AssemblyFlags'
`

**Comment by JohnBaracuda** [comment]
Should be fixed in 3.5.3
