### ISSUE TITLE
Creating a Settings file creates an empty "Resources 1" folder

### ISSUE THREAD

**Issue by AldeRoberge** [JohnBaracuda/Runtime-Monitoring#19]
Hey, first, really cool stuff. I use it in every project.

There is a very tiny problem with the Settings creation : it creates a folder named Resources 1.

![image](https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring/assets/4276275/69dc90ac-dae3-4aed-b4fb-7cc0ce8547b8)

Also, the Settings is not automatically created when missing, resulting in a Null reference exception.

**Comment by JohnBaracuda** [comment]
Thank you :) both issues should be fixed in 3.5.4
