### ISSUE TITLE
WebGL UI is not updating

### ISSUE THREAD

**Issue by AldeRoberge** [JohnBaracuda/Runtime-Monitoring#20]
In WebGL :

![image](https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring/assets/4276275/5c5a68c9-3bea-46ae-af55-3307cb1b9115)

In Editor :

![image](https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring/assets/4276275/421812c2-8284-4ff4-817b-bd7e09480459)

Current event time elapsed (just a simple float value) does not update, nor does any other value.

**Comment by JohnBaracuda** [comment]
The issue should be fixed in version 3.5.4, although I can only verify this for Unity 2019.4. If you encounter the problem in your version, please feel free to reopen this issue.

**Comment by rmpasswd** [comment]
Hello,
is there a built in function that can update the labels? In my case the label values come from a websocket broker, but the text UI updates only if i do a mouse click on the screen....

**Comment by JohnBaracuda** [comment]
There might be a way. For individual elements, look at the MUpdateEvent attribute. This lets you pass the name of an event that, when invoked, will force the monitored element to update. If that doesn't help, you can get all elements using Monitor.Registry.GetMonitorHandles() or Monitor.Registry.GetMonitorHandlesForTarget(). Then, call Refresh() on the individual handles. However, I am not familiar with most of the quirks when using WebGL, so keep that in mind.
