### ISSUE TITLE
exmaple scene broken

### ISSUE THREAD

**Issue by XeonG** [JohnBaracuda/Runtime-Monitoring#25]
Failed to create Physics Mesh from source mesh. One of the triangles is too large. It's recommended to tesselate the large triangles. Source mesh name: Plattform_01
—
at bool UnityEditor.SceneManagement.EditorSceneManager.ReloadScene(Scene scene)
void UnityEditor.SceneHierarchy.DiscardChangesInSelectedScenes(object userData)
void UnityEditor.GenericMenu.CatchMenu(object userData, string[] options, int selected)

**Comment by JohnBaracuda** [comment]
Hey, apologies for the delayed response. Could you provide more details on where or how exactly this issue occurs? The example scene runs perfectly fine on my end with a fresh install of Unity 2022.3.19.1. I suspect the issue might relate to the scale of the platforms in the example scene. However, if it doesn't break anything, my inclination is to leave it as is for now.
