### ISSUE TITLE
How to just get the actual value? as a string

### ISSUE THREAD

**Issue by XeonG** [JohnBaracuda/Runtime-Monitoring#26]
without any formatting when making a new ui override?

**Comment by JohnBaracuda** [comment]
Added IMonitorHandle.GetValueAsObject() in 3.6.0 to get a monitored object without any formattig.

**Comment by XeonG** [comment]
cool thanks, bit ages since I last looked at the code to know what I was doing with wanting this now.. .but hopefully will find it again

**Comment by JohnBaracuda** [comment]
Glad I could help even after the long radio silence :)
