### ISSUE TITLE
Issue with conditional display code

### ISSUE THREAD

**Issue by PooperPig** [JohnBaracuda/Runtime-Monitoring#29]
I took the code from the documentation
public class PlayerAccelerate : MonoBehaviour
```
{

	[Monitor]
	[MShowIf(monitor)]
	private bool IsAlive { get; }

	[SerializeField] private bool monitor = true;
```

which gives me an error on the 'monitor' field
"An object reference is required for the non-static field, method, or property 'PlayerAccelerate.monitor'"

It would be great if it did work, as I want to be able to turn monitoring on and off for various classes in my game...

**Comment by JohnBaracuda** [comment]
I think this is just an issue with the documentation. It should use the nameof() keyword to pass in the name of the monitor bool instead of passing in the bool directly. This should work:

```c#
[Monitor]
[MShowIf(nameof(monitor))]
private bool IsAlive { get; }

[SerializeField] private bool monitor = true;
```

**Comment by PooperPig** [comment]
Brilliant, I'll give it a go.
