### ISSUE TITLE
Error upon importing assets

### ISSUE THREAD

**Issue by TrapShooter** [JohnBaracuda/Runtime-Monitoring#3]
Same as before but a bit different now!

Assets\Third Party\Baracuda\Assets\Baracuda\Monitoring\Internal\Units\ValueUnit.cs(149,110): error CS1061: 'T' does not contain a definition for 'ConvertUnsafe' and no accessible extension method 'ConvertUnsafe' accepting a first argument of type 'T' could be found (are you missing a using directive or an assembly reference?)

**Comment by JohnBaracuda** [comment]
I will fix it in the next patch. If you don't want to wait, you should be able to fix it by replacing it
```ConvertUnsafe``` with ```ConvertFast```

**Comment by TrapShooter** [comment]
thank you!
