### ISSUE TITLE
[Question] How to set the default size of fonts or the scaling of UI

### ISSUE THREAD

**Issue by LastAssertor** [JohnBaracuda/Runtime-Monitoring#30]
Because my computer screen is too small.

**Comment by JohnBaracuda** [comment]
If you are using the TextMeshPro version, you can just set the scale factor of the Canvas Scaler component on the prefab.

![image](https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring/assets/58704151/6e6cfc6e-b579-44aa-82dc-76b2bb768881)

If you are using the IMGUI version imported from the samples, there is actually a custom scale setting.

![image](https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring/assets/58704151/eadf65c1-de87-4383-bb2e-f1b42e3b1790)

If you are using neither of them, I would recommend importing and using the TextMeshPro resources from the samples. This allows you to fully customize every aspect of the UI. Once imported, open the monitoring settings (Tools => Runtime Monitoring => Settings) and then drag the MonitoringUI prefab from the samples folder into the Monitoring UI Override field. You can then change the scale factor or even the scale mode of the UI using the Canvas Scaler component of the prefab.
