### ISSUE TITLE
monitored field appears twice in runtime window

### ISSUE THREAD

**Issue by androvisuals** [JohnBaracuda/Runtime-Monitoring#4]
`using Baracuda.Monitoring;`
`using Baracuda.Monitoring.API;`
<br>
`[Monitor] [SerializeField] int aggroCounter = 0;`
 `[Monitor] [SerializeField] float decisionScoreForCover = 0;`

in Start I have 
`MonitoringManager.RegisterTarget(this);`

this results in the fields appearing twice. Shouldn't they only appear once?
I removed the SerializeField attribute but this didn't change anything.
Any and all help appreciated.

![image](https://user-images.githubusercontent.com/19530188/169688111-3cfd3ec9-ee0e-4e92-9a5e-dfc677050dc6.png)

**Comment by JohnBaracuda** [comment]
Hey, I was unable to reproduce this using the same code. Some suggestrions I have:
+ Check that you don't do both inherit from ```MonitoredBehaviour``` and register the object in Start.
+ Check that you don't accidentally call ```Start``` a second time.
+ If it's a ```MonoBehaviour```, check if there is more than one instance of it in your scene. 
+ Also call ```MonitoringManager.UnregisterTarget(this);``` in OnDestory.

If it's still not working I would need a little bit more information about version, what you class is inheriting from etc.
Hope that this may help :)

**Comment by androvisuals** [comment]
Hi there, 
So it was my mistake. I have a class where I use override behavior. So it was getting called twice on start, even though I "only" had it inside the start function of the class ;-)

I now moved the MonitoringManager code to the class the rest inherit from and it all appears only once, and now works perfectly across all the scripts that use it.
The code below is to show what now works correctly for me.
An amazing asset, glad you've shared it with the world <3
Thanks for the speedy reply and help!
```
using Baracuda.Monitoring.API;
public class StateAI : MonoBehaviour
{
    public Soldier soldier;
    protected virtual void Start()
    {
        MonitoringManager.RegisterTarget(this);
    }

    public virtual void AwakeSoldierAI() { }
    public virtual void StartSoldierAI() { }
    public virtual void UpdateSoldierAI() { }
    public virtual void LateUpdateSoldierAI() { }
}```
